# heavy_yolo_classifier.py
#
# GPU selection uses CUDA_VISIBLE_DEVICES so that the chosen physical GPU
# appears as cuda:0.  When this file is run standalone the selection happens
# BEFORE any CUDA library is imported (two-phase import structure).
# When imported as a module, the caller (main.py) has already set the var.

# ── Phase 0: non-CUDA imports + project path ────────────────────────
import os
import sys
from pathlib import Path
import time
import csv
from typing import Optional

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

# ── Phase 1: GPU selection when running standalone ──────────────────
_PHYSICAL_GPU_INDEX = 0

if __name__ == "__main__":
    from gpu_utils import select_gpu
    _PHYSICAL_GPU_INDEX = select_gpu()

# ── Phase 2: CUDA-heavy imports (CUDA_VISIBLE_DEVICES is now set) ──
import torch
from ultralytics import YOLO
import numpy as np
from PIL import Image
import cv2

from saliency_methods.frame_diff import load_img_paths
from eval_tools.performance_eval.system_monitor import SystemMonitor
# from sound_maker import make_sound, coco_ids_to_names

delay_ms = 1

"""
Available models (change 'weight'):
"yolo11s.pt" : YOLO Speed (relatively light-weight, not that accurate)
"yolo11l.pt" : YOLO Light (moderate heaft, relatively accurate)
"yolo11x.pt": YOLO X (heaviest, Xtra accurate)
"""

# ============================================================
#  Fine-tuned Model Configuration
# ============================================================
# Path to the fine-tuned weights (generated by finetune_yolo.py)
FINETUNED_WEIGHTS = {
    "yolo11s": str(_PROJECT_ROOT / "finetune_output" / "weights" / "yolo11s_finetuned_cars.pt"),
    "yolo11l": str(_PROJECT_ROOT / "finetune_output" / "weights" / "yolo11l_finetuned_cars.pt"),
    "yolo11x": str(_PROJECT_ROOT / "finetune_output" / "weights" / "yolo11x_finetuned_cars.pt"),
}

# Default fine-tuned model to use when use_finetuned=True
DEFAULT_FINETUNED_MODEL = "yolo11s"



def _get_best_device():
    """Auto-detect the best available device: cuda > mps > cpu.
    Returns an Ultralytics-compatible device specifier:
      - int 0  for first CUDA GPU  (Ultralytics preferred format)
      - "mps" for Apple Silicon
      - "cpu" as fallback
    """
    if torch.cuda.is_available():
        return 0          # Ultralytics uses int GPU index
    elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return "mps"
    else:
        return "cpu"


def _normalize_device(device):
    """Normalise any device specification to an Ultralytics-compatible value.

    Ultralytics works most reliably with **integer GPU indices** (0, 1, …)
    rather than PyTorch-style strings like ``"cuda"`` or ``"cuda:0"``.
    On NVIDIA Jetson this is especially important — passing the string
    ``"cuda"`` can cause Ultralytics to silently fall back to CPU.

    Accepted inputs → output:
        None            → auto-detect (_get_best_device)
        0 / 1 / int     → kept as-is
        "cuda"          → 0
        "cuda:N"        → N (int)
        "mps"           → "mps"
        "cpu"           → "cpu"
    """
    if device is None:
        return _get_best_device()

    # Already an integer GPU index — pass through
    if isinstance(device, int):
        return device

    device_str = str(device).lower().strip()
    if device_str == "cuda":
        return 0
    if device_str.startswith("cuda:"):
        try:
            return int(device_str.split(":")[1])
        except (ValueError, IndexError):
            return 0
    if device_str == "mps":
        return "mps"
    # Anything else (including "cpu")
    return "cpu"


def get_weight_path(weight: str = "yolo11s.pt", use_finetuned: bool = False) -> str:
    """
    Get the appropriate weight path based on configuration.
    
    Args:
        weight: Base model name (e.g., "yolo11s.pt", "yolo11x.pt")
        use_finetuned: If True, return path to fine-tuned weights
        
    Returns:
        Path to the weight file
    """
    if not use_finetuned:
        return weight
    
    # Extract model variant from weight name (e.g., "yolo11s" from "yolo11s.pt")
    model_key = weight.replace(".pt", "")
    
    if model_key in FINETUNED_WEIGHTS:
        finetuned_path = FINETUNED_WEIGHTS[model_key]
        if os.path.exists(finetuned_path):
            print(f"[get_weight_path] Using fine-tuned weights: {finetuned_path}")
            return finetuned_path
        else:
            print(f"[get_weight_path] WARNING: Fine-tuned weights not found at {finetuned_path}")
            print(f"[get_weight_path] Run finetune_yolo.py first to generate fine-tuned weights.")
            print(f"[get_weight_path] Falling back to pretrained: {weight}")
            return weight
    else:
        print(f"[get_weight_path] WARNING: No fine-tuned model configured for {model_key}")
        print(f"[get_weight_path] Available: {list(FINETUNED_WEIGHTS.keys())}")
        print(f"[get_weight_path] Falling back to pretrained: {weight}")
        return weight


class HeavyYoloClassifier:
    """
    Ultralytics YOLOv11:
        predict_image(PIL.Image) -> (annotated_pil, boxes_xywh, classes, scores)
        
    Args:
        weight: Model weight file (e.g., "yolo11s.pt", "yolo11x.pt")
        imgsz: Image size for inference
        conf: Confidence threshold
        device: Device to run on ("cuda", "mps", "cpu", or None for auto-detect)
        use_finetuned: If True, use fine-tuned weights instead of pretrained
    """
    def __init__(self, weight: str = "yolo11s.pt", imgsz: int = 1280, conf: float = 0.25, 
                 device = None, use_finetuned: bool = False):
        # Normalise to Ultralytics-compatible device (int GPU index, "mps", or "cpu")
        self.device = _normalize_device(device)
        
        # Human-readable device name for logging
        if isinstance(self.device, int):
            self._device_display = f"cuda:{self.device}" if torch.cuda.is_available() else "cpu"
        else:
            self._device_display = str(self.device)
        
        # Get the appropriate weight path (finetuned or pretrained)
        self.weight_path = get_weight_path(weight, use_finetuned)
        self.use_finetuned = use_finetuned
        
        self.model = YOLO(self.weight_path)
        # Move model to the selected device
        self.model.to(self.device)
        
        self.imgsz = imgsz
        self.conf = conf
        self.total_yolo_time = 0.0
        
        model_type = "fine-tuned" if use_finetuned else "pretrained"
        print(f"[HeavyYoloClassifier] Loaded {self.weight_path} ({model_type}) on device: {self._device_display}")
        
        # ── GPU warmup: run a dummy inference so CUDA kernels are compiled
        #    before any timing begins. ──
        if isinstance(self.device, int) and torch.cuda.is_available():
            self._warmup()
    
    # ----------------------------------------------------------------
    def _warmup(self, n: int = 2):
        """Run *n* dummy forward passes to trigger CUDA kernel compilation.
        The time is NOT added to ``total_yolo_time``."""
        import warnings
        dummy = Image.new("RGB", (self.imgsz, self.imgsz), color=(128, 128, 128))
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            for _ in range(n):
                self.model.predict(
                    source=dummy,
                    imgsz=self.imgsz,
                    conf=self.conf,
                    verbose=False,
                    device=self.device,
                )
        # Verify the model actually ran on GPU
        if torch.cuda.is_available():
            gpu_mem = torch.cuda.memory_allocated()
            if gpu_mem > 0:
                print(f"[HeavyYoloClassifier] ✅ GPU warmup OK — {gpu_mem / 1024**2:.1f} MB allocated on GPU")
            else:
                print(f"[HeavyYoloClassifier] ⚠️  WARNING: GPU memory is 0 after warmup — model may be on CPU!")

    @staticmethod
    def _xyxy_to_xywh(xyxy: np.ndarray) -> np.ndarray:
        # xyxy -> xywh (top-left x,y, width, height)
        out = xyxy.copy()
        out[:, 2] = out[:, 2] - out[:, 0]  # w = x2-x1
        out[:, 3] = out[:, 3] - out[:, 1]  # h = y2-y1
        out[:, 0] = out[:, 0]              # x = x1
        out[:, 1] = out[:, 1]              # y = y1
        return out

    def predict_image(self, img_pil: Image.Image):
        # Ultralytics can take numpy/PIL directly
        # Returns a list of Results; take index 0

        start = time.time() #prediction start time
        res = self.model.predict(source=img_pil, 
                                 imgsz=self.imgsz, 
                                 conf=self.conf, 
                                 verbose=False,
                                 device=self.device
                                )[0]

        # Annotated frame from Ultralytics is BGR np.ndarray
        ann_bgr = res.plot()  # BGR for OpenCV
        # Convert BGR->RGB then to PIL
        ann_rgb = ann_bgr[..., ::-1]
        annotated_pil = Image.fromarray(ann_rgb)

        # Boxes, classes, scores
        if res.boxes is None or len(res.boxes) == 0:
            return annotated_pil, None, None, None

        xyxy = res.boxes.xyxy.cpu().numpy()
        conf = res.boxes.conf.cpu().numpy()
        cls  = res.boxes.cls.cpu().numpy().astype(int)

        # Convert to xywh to match the structure of TinyYOLO
        boxes_xywh = self._xyxy_to_xywh(xyxy)
        end = time.time() #prediction end time
        self.total_yolo_time += (end - start)

        return annotated_pil, boxes_xywh, cls, conf
    

    def _get_total_yolo_time(self) -> float:
        return self.total_yolo_time

    # ── Batch prediction (single forward pass for N images) ──────────
    def predict_batch(self, images: list):
        """
        Run YOLO on a list of PIL images in ONE batched forward pass.

        Args:
            images: List of PIL.Image.Image (can be different sizes; Ultralytics
                    handles letterbox-padding internally).

        Returns:
            list of (annotated_pil, boxes_xywh, classes, scores)
            One tuple per input image, same format as predict_image().
        """
        if not images:
            return []

        start = time.time()
        results = self.model.predict(
            source=images,
            imgsz=self.imgsz,
            conf=self.conf,
            verbose=False,
            device=self.device,
        )
        elapsed = time.time() - start
        self.total_yolo_time += elapsed

        outputs = []
        for res in results:
            ann_bgr = res.plot()
            ann_rgb = ann_bgr[..., ::-1]
            annotated_pil = Image.fromarray(ann_rgb)

            if res.boxes is None or len(res.boxes) == 0:
                outputs.append((annotated_pil, None, None, None))
                continue

            xyxy = res.boxes.xyxy.cpu().numpy()
            conf = res.boxes.conf.cpu().numpy()
            cls  = res.boxes.cls.cpu().numpy().astype(int)
            boxes_xywh = self._xyxy_to_xywh(xyxy)
            outputs.append((annotated_pil, boxes_xywh, cls, conf))

        return outputs
    

def print_timing_summary(
    n_frames: int,
    total_time: float,
    yolo_tot: Optional[float],
    imageio_tot: Optional[float] = None,
    overlay_tot: Optional[float] = None,
    title: str = "YOLOv11 — Timing Summary",
    model_name: str = "YOLOv11",
    save_csv: Optional[str] = None,
):
    """Pretty timing report with per-frame averages and an OTHER bucket.
    CSV schema matches Attention Grid's print_timing_summary for easy comparisons.
    """
    def _fmt(val: Optional[float]) -> str:
        return f"{val:>9.5f}s" if isinstance(val, (int, float)) else f"{'-':>9}"

    def _avg(val: Optional[float]) -> Optional[float]:
        if isinstance(val, (int, float)) and n_frames:
            return val / n_frames
        return None

    # None -> 0 for OTHER math
    _y = yolo_tot or 0.0
    _i = imageio_tot or 0.0
    _o = overlay_tot or 0.0

    known_sum = _y + _i + _o
    other_tot = max(0.0, total_time - known_sum)

    yolo_avg     = _avg(yolo_tot)
    overlay_avg  = _avg(overlay_tot)
    imageio_avg  = _avg(imageio_tot)
    other_avg    = _avg(other_tot)
    total_wo_io  = total_time - (_i if isinstance(imageio_tot, (int, float)) else 0.0)
    fps          = (n_frames / total_time) if (n_frames and total_time > 0) else None

    # ---- Console print ----
    print("\n" + "=" * 70)
    print(title.center(70))
    print("=" * 70)
    print(f"Frames processed: {n_frames}")
    if fps is not None:
        print(f"Approx FPS: {fps:.2f}")
    print("-" * 70)
    print(f"{model_name:<26} Total: {_fmt(yolo_tot)}   Average: {_fmt(yolo_avg)}")
    print(f"{'Overlay (grid/UI)':<26} Total: {_fmt(overlay_tot)}   Average: {_fmt(overlay_avg)}")
    print(f"{'Image I/O':<26} Total: {_fmt(imageio_tot)}   Average: {_fmt(imageio_avg)}")
    print("-" * 70)
    print(f"{'OTHER (prints, etc)':<26} Total: {_fmt(other_tot)}   Average: {_fmt(other_avg)}")
    print("-" * 70)
    print(f"{'TOTAL':<26} Total: {total_time:>9.5f}s")
    print("-" * 70)
    print(f"{'TOTAL w/o I/O':<26} Total: {total_wo_io:>9.5f}s")
    print("=" * 70)

    # ---- CSV row with SAME COLUMNS as Attention Grid version ----
    if save_csv:
        row = {
            "title": title,
            "model_name": model_name,
            "frames": n_frames,
            "fps": f"{fps:.4f}" if fps is not None else "-",
            "total_time_s": f"{total_time:.6f}",

            # No FrameDiff/Tiler in heavy path -> '-'
            "framediff_total_s": "-",
            "framediff_avg_s":   "-",
            "tiler_total_s": "-",
            "tiler_avg_s":   "-",

            # Reuse the same columns for the detector timings so files align:
            # Put heavy YOLO totals into the TinyYOLO-labeled columns (schema compatibility).
            "yolo_total_s": f"{yolo_tot:.6f}" if isinstance(yolo_tot, (int, float)) else "-",
            "yolo_avg_s":   f"{yolo_avg:.6f}" if isinstance(yolo_avg, (int, float)) else "-",

            "overlay_total_s": f"{overlay_tot:.6f}" if isinstance(overlay_tot, (int, float)) else "-",
            "overlay_avg_s":   f"{overlay_avg:.6f}" if isinstance(overlay_avg, (int, float)) else "-",
            "imageio_total_s": f"{imageio_tot:.6f}" if isinstance(imageio_tot, (int, float)) else "-",
            "imageio_avg_s":   f"{imageio_avg:.6f}" if isinstance(imageio_avg, (int, float)) else "-",
            "other_total_s": f"{other_tot:.6f}",
            "other_avg_s":   f"{other_avg:.6f}" if isinstance(other_avg, (int, float)) else "-",
            "total_wo_io_s": f"{total_wo_io:.6f}",
        }
        fieldnames = list(row.keys())
        try:
            need_header = False
            try:
                with open(save_csv, "r", newline="") as f:
                    need_header = (f.read(1) == "")
            except FileNotFoundError:
                need_header = True

            with open(save_csv, "a", newline="") as f:
                writer = csv.DictWriter(f, fieldnames=fieldnames)
                if need_header:
                    writer.writeheader()
                writer.writerow(row)
        except Exception as e:
            print(f"[WARN] Failed to write CSV '{save_csv}': {e}")
    print("=" * 70)





def save_yolo_txt(
    img_pil: Image.Image,
    boxes_xywh,
    classes,
    scores,
    label_dir: str,
    image_path: str,
    keep_coco_ids=None,
    coco_to_local=None,
    min_conf: float = 0.0,
):
    """
    Save detections in YOLO txt format for a single image.

    YOLO txt format (per line):
        <class_id> <x_center> <y_center> <width> <height>
    all normalized in [0, 1].

    Parameters
    ----------
    img_pil : PIL.Image.Image
        The original image (used to get width/height).
    boxes_xywh : np.ndarray or None
        Array of shape (N, 4): [x1, y1, w, h] in pixels (top-left format).
    classes : np.ndarray or None
        Array of shape (N,): COCO class indices (ints).
    scores : np.ndarray or None
        Array of shape (N,): confidence scores (floats). Can be None.
    label_dir : str
        Directory where the .txt labels will be saved.
    image_path : str
        Path to the image file; used to derive the txt filename.
    keep_coco_ids : set[int] or None
        If not None, keep only detections whose COCO class id is in this set.
        If None, keep all classes.
    coco_to_local : dict[int, int] or None
        Mapping from COCO class id -> local dataset class id.
        If None, we use the COCO id directly as class_id.
    min_conf : float
        Minimum confidence threshold for saving a detection.
        Ignored if scores is None.
    """
    os.makedirs(label_dir, exist_ok=True)

    # Derive txt filename from image_path
    base_name = os.path.splitext(os.path.basename(image_path))[0]
    label_path = os.path.join(label_dir, base_name + ".txt")

    # No detections: write empty file
    if boxes_xywh is None or classes is None or len(classes) == 0:
        with open(label_path, "w") as f:
            pass
        return

    img_w, img_h = img_pil.size
    lines = []

    # If scores is None, treat all detections as above threshold
    if scores is None:
        scores = [1.0] * len(classes)

    for box, cls_id, score in zip(boxes_xywh, classes, scores):
        if score < min_conf:
            continue

        # Filter by COCO class id if keep_coco_ids is given
        if keep_coco_ids is not None and cls_id not in keep_coco_ids:
            continue

        # Map COCO id -> local id if mapping provided, else use COCO id directly
        if coco_to_local is not None:
            if cls_id not in coco_to_local:
                continue
            class_id = coco_to_local[cls_id]
        else:
            class_id = int(cls_id)

        x1, y1, bw, bh = box  # pixel coords (top-left + w,h)

        # Convert to YOLO normalized (x_center, y_center, w, h)
        x_c = (x1 + bw / 2.0) / img_w
        y_c = (y1 + bh / 2.0) / img_h
        bw_n = bw / img_w
        bh_n = bh / img_h

        # Clip to [0, 1] for safety
        x_c = max(0.0, min(1.0, x_c))
        y_c = max(0.0, min(1.0, y_c))
        bw_n = max(0.0, min(1.0, bw_n))
        bh_n = max(0.0, min(1.0, bh_n))

        lines.append(f"{class_id} {x_c:.6f} {y_c:.6f} {bw_n:.6f} {bh_n:.6f} {float(score):.6f}")

    # Write file (possibly empty if nothing passed filters)
    with open(label_path, "w") as f:
        for line in lines:
            f.write(line + "\n")




if __name__ == "__main__":
    monitor = SystemMonitor(gpu_index=_PHYSICAL_GPU_INDEX)

    total_time = 0.0
    total_overlay_time = 0.0
    classifier = HeavyYoloClassifier()

    # ==========================================================================

    # Single Image TEST
    # count the time taken for prediction

    # t_io0 = time.perf_counter()

    # img = Image.open("./dataset_20fps/ezgif-frame-001.png").convert("RGB")
    # ann_img, boxes, classes, scores = classifier.predict_image(img)

    # total_time += (time.perf_counter() - t_io0)

    # print("Boxes:", boxes)
    # print("Classes:", classes)
    # print("Scores:", scores)
    # print(f"Time taken for prediction: {total_time:.4f} seconds")

    # ann_img.show()

    # ==========================================================================


    path = str(_PROJECT_ROOT / "dataset_20fps")
    # path = "sample_video_frames"
    
    img_paths = load_img_paths(path=path, print_paths=True)

    labels_out_dir = "./yolov11s_labels"

    # for idx, img_path in enumerate(img_paths):
    #     print(f"Processing frame {idx+1}/{len(img_paths)}: {img_path}")
    #     img = Image.open(img_path).convert("RGB")
    #     ann_img, boxes, classes, scores = classifier.predict_image(img)
    #     ann_img.show()
    #     cv2.waitKey(1)



    total_time_start   = time.perf_counter()
    total_imageio_time = 0.0
    total_overlay_time = 0.0

    # Headless-safe: save frames to disk instead of cv2.imshow
    vis_dir = str(_PROJECT_ROOT / "vis_output_heavy_yolo")
    os.makedirs(vis_dir, exist_ok=True)

    frames_done = 0

    try:
        for idx, img_path in enumerate(img_paths):
            print(f"Processing frame {idx+1}/{len(img_paths)}: {img_path}")

            # Image I/O (disk only)
            t_io0 = time.perf_counter()
            with Image.open(img_path) as im:
                img = im.convert("RGB")
            total_imageio_time += (time.perf_counter() - t_io0)

            # YOLOV11
            ann_img, boxes, classes, scores = classifier.predict_image(img)
            print(f"DETAILS: {boxes, classes, scores}")

            # save_yolo_txt(
            #     img_pil=img,
            #     boxes_xywh=boxes,
            #     classes=classes,
            #     scores=scores,
            #     label_dir=labels_out_dir,
            #     image_path=img_path,
            #     keep_coco_ids=None,      # only cars; set to None to keep all classes
            #     coco_to_local=None, # car -> 0
            #     min_conf=0.25,               # match your conf if you want
            # )


            # make_sound(coco_ids_to_names(classes, "coco_classes.txt"))

            # Overlay/UI — save to disk (headless-safe)
            t_ui0 = time.perf_counter()
            ann_bgr = cv2.cvtColor(np.array(ann_img), cv2.COLOR_RGB2BGR)
            # cv2.imwrite(os.path.join(vis_dir, f"frame_{idx+1:04d}.png"), ann_bgr)
            

            # visualising the overlay with OpenCV (optional, can be slow and not headless-safe)
            ann_bgr = cv2.cvtColor(np.array(ann_img), cv2.COLOR_RGB2BGR)
            cv2.imshow("YOLOv11 Overlay", ann_bgr)
            cv2.waitKey(delay_ms)


            total_overlay_time += (time.perf_counter() - t_ui0)
            monitor.sample() # sample once per frame

            frames_done = idx + 1

    except KeyboardInterrupt:
        print("\n[INFO] Interrupted by user.")
    finally:
        try:
            cv2.destroyAllWindows()
        except cv2.error:
            pass  # headless build has no GUI

    total_time_end = time.perf_counter()
    total_time = total_time_end - total_time_start

    print_timing_summary(
        n_frames=frames_done,
        total_time=total_time,
        yolo_tot=classifier._get_total_yolo_time(),
        imageio_tot=total_imageio_time,
        overlay_tot=total_overlay_time,
        model_name="YOLOv11-X",
        # save_csv="timings_yolov11x.csv", 
    )


    monitor.report()
